DROP TABLE IF EXISTS school_stats_2025;

CREATE TABLE school_stats_2025 (
    rk INT,
    school VARCHAR(255),
    games INT,
    wins INT,
    losses INT,
    win_pct FLOAT,
    srs FLOAT,
    sos FLOAT,
    conf_wins INT,
    conf_losses INT,
    home_wins INT,
    home_losses INT,
    away_wins INT,
    away_losses INT,
    points_for FLOAT,
    points_against FLOAT,
    minutes_played INT,
    fg_made INT,
    fg_attempted INT,
    fg_pct FLOAT,
    three_made INT,
    three_attempted INT,
    three_pct FLOAT,
    ft_made INT,
    ft_attempted INT,
    ft_pct FLOAT,
    off_reb INT,
    total_reb INT,
    assists INT,
    steals INT,
    blocks INT,
    turnovers INT,
    fouls INT
);
